### ISSUE TITLE
Document (or script) process for building SD/MMC image from generates root filesystem

### ISSUE THREAD

**Issue by pixdrift** [sipeed/LonganPi-3H-SDK#13]
Hi Sipeed devs,

Thanks for putting together these scripts, they provide a very clean method of rebuilding the root filesystem that works reliably.

I am interested in the process that Sipeed use to generate full SD and EMMC images using the root filesystem generated from this repository (images here):
https://wiki.sipeed.com/hardware/en/longan/h618/lpi3h/3_images.html

Could this process be documented in this repository with a `mkimage.sh` perhaps? as it would be useful for people to be able to rebuild the Sipeed images end to end.

**Comment by wu-yue-yu** [comment]
https://wiki.sipeed.com/hardware/en/longan/h618/lpi3h/7_develop_mainline.html#Make-a-boot-TF-card-image

**Comment by pixdrift** [comment]
Thankyou @wu-yue-yu, your documentation is excellent! and apologies I didn't see this when browsing the site.

**Comment by wu-yue-yu** [comment]
> Thankyou @wu-yue-yu, your documentation is excellent! and apologies I didn't see this when browsing the site.

I'll add some descriptions in other pages like imges and burn_image as well.
