### ISSUE TITLE
mkrootfs.sh报错

### ISSUE THREAD

**Issue by songyq26** [sipeed/LonganPi-3H-SDK#5]
mkdir: cannot create directory ‘build’: File exists
+ genrootfs
+ echo '
deb https://mirrors.bfsu.edu.cn/debian/ testing main contrib non-free non-free-firmware
deb https://mirrors.bfsu.edu.cn/debian/ testing-updates main contrib non-free non-free-firmware
deb https://mirrors.bfsu.edu.cn/debian/ testing-backports main contrib non-free non-free-firmware
deb https://mirrors.bfsu.edu.cn/debian-security/ testing-security main contrib non-free non-free-firmware
'
+ mmdebstrap --architectures=arm64 -v -d '--include=ca-certificates locales dosfstools binutils file    tree sudo bash-completion memtester openssh-server wireless-regdb       wpasupplicant systemd-timesyncd usbutils parted systemd-sysv    iperf3 stress-ng avahi-daemon tmux screen i2c-tools net-tools    ethtool ckermit lrzsz minicom picocom btop neofetch iotop htop  bmon e2fsprogs nvi tcpdump alsa-utils squashfs-tools evtest     bluez bluez-hcidump bluez-tools btscanner bluez-alsa-utils      device-tree-compiler debian-archive-keyring connman-gtk chromium linux-cpupower task-xfce-desktop xfce4-terminal xfce4-screenshooter     pulseaudio-module-bluetooth blueman fonts-noto-core fonts-noto-cjk      fonts-noto-mono fonts-noto-ui-core tango-icon-theme'
I: automatically chosen mode: unshare
I: arm64 cannot be executed, falling back to qemu-user
I: No SUITE specified, expecting sources.list on standard input
I: Reading sources.list from standard input...
I: using /tmp/mmdebstrap.LfsHc0Bl2n as tempdir
D: aptopts: []
D: architectures: arm64
D: components: main
D: customize_hook: []
D: dpkgopts: []
D: essential_hook: []
D: foreignarchs: []
D: havemknod: 0
D: include: ca-certificates locales dosfstools binutils file    tree sudo bash-completion memtester openssh-server wireless-regdb       wpasupplicant systemd-timesyncd usbutils parted systemd-sysv    iperf3 stress-ng avahi-daemon tmux screen i2c-tools net-tools   ethtool ckermit lrzsz minicom picocom btop neofetch iotop htop   bmon e2fsprogs nvi tcpdump alsa-utils squashfs-tools evtest     bluez bluez-hcidump bluez-tools btscanner bluez-alsa-utils      device-tree-compiler debian-archive-keyring connman-gtk chromium        linux-cpupower task-xfce-desktop xfce4-terminal xfce4-screenshooter      pulseaudio-module-bluetooth blueman fonts-noto-core fonts-noto-cjk      fonts-noto-mono fonts-noto-ui-core tango-icon-theme
D: maketar: 1
D: mode: unshare
D: nativearch: arm64
D: noop: []
D: qemu: aarch64
D: root: /tmp/mmdebstrap.LfsHc0Bl2n
D: setup_hook: []
D: sourceslist:
deb https://mirrors.bfsu.edu.cn/debian/ testing main contrib non-free non-free-firmware
deb https://mirrors.bfsu.edu.cn/debian/ testing-updates main contrib non-free non-free-firmware
deb https://mirrors.bfsu.edu.cn/debian/ testing-backports main contrib non-free non-free-firmware
deb https://mirrors.bfsu.edu.cn/debian-security/ testing-security main contrib non-free non-free-firmware

D: target: -
D: variant: important
I: running apt-get update...
Get:1 https://mirrors.bfsu.edu.cn/debian testing InRelease [156 kB]
Err:1 https://mirrors.bfsu.edu.cn/debian testing InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
Get:2 https://mirrors.bfsu.edu.cn/debian testing-updates InRelease [45.1 kB]
Err:2 https://mirrors.bfsu.edu.cn/debian testing-updates InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
Get:3 https://mirrors.bfsu.edu.cn/debian testing-backports InRelease [45.2 kB]
Err:3 https://mirrors.bfsu.edu.cn/debian testing-backports InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
Get:4 https://mirrors.bfsu.edu.cn/debian-security testing-security InRelease [43.5 kB]
Err:4 https://mirrors.bfsu.edu.cn/debian-security testing-security InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 54404762BBB6E853 NO_PUBKEY BDE6D2B9216EC7A8
Reading package lists...
W: GPG error: https://mirrors.bfsu.edu.cn/debian testing InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
E: The repository 'https://mirrors.bfsu.edu.cn/debian testing InRelease' is not signed.
W: GPG error: https://mirrors.bfsu.edu.cn/debian testing-updates InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
E: The repository 'https://mirrors.bfsu.edu.cn/debian testing-updates InRelease' is not signed.
W: GPG error: https://mirrors.bfsu.edu.cn/debian testing-backports InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
E: The repository 'https://mirrors.bfsu.edu.cn/debian testing-backports InRelease' is not signed.
W: GPG error: https://mirrors.bfsu.edu.cn/debian-security testing-security InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 54404762BBB6E853 NO_PUBKEY BDE6D2B9216EC7A8
E: The repository 'https://mirrors.bfsu.edu.cn/debian-security testing-security InRelease' is not signed.
E: apt-get update -oAPT::Status-Fd=<$fd> -oDpkg::Use-Pty=false failed at /usr/bin/mmdebstrap line 126.
        main::error("apt-get update -oAPT::Status-Fd=<\$fd> -oDpkg::Use-Pty=false f"...) called at /usr/bin/mmdebstrap line 649
        main::run_progress(CODE(0x5614a2072158), CODE(0x5614a1e61e40), CODE(0x5614a1e61cd8), "/tmp/mmdebstrap.LfsHc0Bl2n") called at /usr/bin/mmdebstrap line 701
        main::run_apt_progress(HASH(0x5614a1fc8b38)) called at /usr/bin/mmdebstrap line 1144
        main::setup(HASH(0x5614a1fc7e20)) called at /usr/bin/mmdebstrap line 2200
        main::__ANON__() called at /usr/bin/mmdebstrap line 471
        main::get_unshare_cmd(CODE(0x5614a1f9bcf8), ARRAY(0x5614a1f5d4b0)) called at /usr/bin/mmdebstrap line 2221
        main::main() called at /usr/bin/mmdebstrap line 2400
I: removing tempdir /tmp/mmdebstrap.LfsHc0Bl2n...

**Comment by wu-yue-yu** [comment]
可以参考[此步骤](https://wiki.sipeed.com/hardware/zh/lichee/th1520/lpi4a/5_desktop.html#%E8%BD%AF%E4%BB%B6%E5%AE%89%E8%A3%85:~:text=%E8%8B%A5%E5%9C%A8%E4%B8%8B%E8%BD%BD%E8%BD%AF%E4%BB%B6%E7%9A%84%E8%BF%87%E7%A8%8B%E4%B8%AD%E9%81%87%E5%88%B0%E7%B1%BB%E4%BC%BC%E4%B8%8B%E9%9D%A2%E7%9A%84%E6%8F%90%E7%A4%BA%E4%BF%A1%E6%81%AF%EF%BC%9A)来添加一下缺失的KEY

**Comment by songyq26** [comment]
我这是在生成文件系统的阶段报错了，问题已经解决，是因为文件系统使用的是Debian，而编译环境却是Ubuntu引发的。
解决步骤如下：

1. 宿主机上执行：sudo apt install debian-archive-keyring
2. mkrootfs.sh修改如下：


#!/usr/bin/env bash

if [ -z "$MMDEBSTRAP" ]
then
	MMDEBSTRAP=mmdebstrap
fi

mkdir build

set -eux

genrootfs() {
echo "
deb https://mirrors.bfsu.edu.cn/debian/ testing main contrib non-free non-free-firmware
deb https://mirrors.bfsu.edu.cn/debian/ testing-updates main contrib non-free non-free-firmware
deb https://mirrors.bfsu.edu.cn/debian/ testing-backports main contrib non-free non-free-firmware
deb https://mirrors.bfsu.edu.cn/debian-security/ testing-security main contrib non-free non-free-firmware
" | $MMDEBSTRAP unstable sid \
  --aptopt='Dir::Etc::Trusted "/usr/share/keyrings/debian-archive-keyring.gpg"' --architectures=arm64 -v -d \
	--include="ca-certificates locales dosfstools binutils file \
	tree sudo bash-completion memtester openssh-server wireless-regdb \
	wpasupplicant systemd-timesyncd usbutils parted systemd-sysv \
	iperf3 stress-ng avahi-daemon tmux screen i2c-tools net-tools \
	ethtool ckermit lrzsz minicom picocom btop neofetch iotop htop \
	bmon e2fsprogs nvi tcpdump alsa-utils squashfs-tools evtest \
	bluez bluez-hcidump bluez-tools btscanner bluez-alsa-utils \
	device-tree-compiler debian-archive-keyring connman-gtk chromium\
	linux-cpupower task-xfce-desktop xfce4-terminal xfce4-screenshooter \
	pulseaudio-module-bluetooth blueman fonts-noto-core fonts-noto-cjk \
	fonts-noto-mono fonts-noto-ui-core tango-icon-theme" > ./build/rootfs.tar
}

# if you want skip debian rootfs build, please comment this line:
genrootfs
cd overlay
for i in *
do
tar --append --file=../build/rootfs.tar $i
done
cd ..
