### ISSUE TITLE
kernel about docker

### ISSUE THREAD

**Issue by windskyxb** [sipeed/LonganPi-3H-SDK#50]
After I have built the Rootfs of Ubuntu using `mkrootfs-ubuntu-cli.sh` and packaged the image, I can install Docker normally. 
But I got an error when I tried to run Docker. 
Use journalctl-u docker.service to check the error report as follows:
`failed to start daemon: Error initializing network controller: error obtaining controller instance: failed to register "bridge" driver: failed to create NAT chain DOCKER: iptables failed: iptables-t nat-N DOCKER: iptables/1.8.7 Failed to initialize nft: Protocol not supported. `
How can I modify the kernel options so that docker works properly?

**Comment by lonerkim** [comment]
I suspect [this](https://github.com/sipeed/LonganPi-3H-SDK/issues/26) also would help [kernel settings](https://github.com/lonerkim/LonganPi-3H-SDK/blob/main/linux/0037-Enable-necessary-modules-for-kubernetes.patch) for docker but that was, non-tech background person's struggle.

so you can try it at your own risk(my 4 Lpi3H successfully boot/run k3s on those setting with TFcards)

**Comment by windskyxb** [comment]
> I suspect [this](https://github.com/sipeed/LonganPi-3H-SDK/issues/26) also would help [kernel settings](https://github.com/lonerkim/LonganPi-3H-SDK/blob/main/linux/0037-Enable-necessary-modules-for-kubernetes.patch) for docker but that was, non-tech background person's struggle.
> 
> so you can try it at your own risk(my 4 Lpi3H successfully boot/run k3s on those setting with TFcards)

Thank you for your reply!

**Comment by windskyxb** [comment]
> I suspect [this](https://github.com/sipeed/LonganPi-3H-SDK/issues/26) also would help [kernel settings](https://github.com/lonerkim/LonganPi-3H-SDK/blob/main/linux/0037-Enable-necessary-modules-for-kubernetes.patch) for docker but that was, non-tech background person's struggle.
> 
> so you can try it at your own risk(my 4 Lpi3H successfully boot/run k3s on those setting with TFcards)

With reference to your modification, I successfully ran Dockers!
