### ISSUE TITLE
Error during the linux build process

### ISSUE THREAD

**Issue by alexlakey1** [sipeed/LonganPi-3H-SDK#6]
I am running the linux build shell script in Ubuntu and I get a configuration error at the point the script tries to make the defconfig:

+ make mrproper
+ make longanpi_3h_defconfig
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  HOSTCC  scripts/kconfig/confdata.o
  HOSTCC  scripts/kconfig/expr.o
  LEX     scripts/kconfig/lexer.lex.c
  YACC    scripts/kconfig/parser.tab.[ch]
  HOSTCC  scripts/kconfig/lexer.lex.o
  HOSTCC  scripts/kconfig/menu.o
  HOSTCC  scripts/kconfig/parser.tab.o
  HOSTCC  scripts/kconfig/preprocess.o
  HOSTCC  scripts/kconfig/symbol.o
  HOSTCC  scripts/kconfig/util.o
  HOSTLD  scripts/kconfig/conf
***
*** Can't find default configuration "arch/arm64/configs/longanpi_3h_defconfig"!
***

Can anyone tell me whether this is a component I am missing, or is this a permissions issue? 

thanks

**Comment by wu-yue-yu** [comment]
Please refer to the **mklinux.sh** in this repo

**Comment by alexlakey1** [comment]
Thanks for your help. Can I check - you mean I have to patch the host system that I build on, not apply the patches after the build is made (to the target Sipeed system)?

**Comment by wu-yue-yu** [comment]
Exactly. The patch should be applied before building. You can check the mklinux.sh and mkuboot.sh for details, the patches will be applied when running the build scripts.

**Comment by alexlakey1** [comment]
Thanks so much for taking the time to help.
